version: '3.12'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: ./client-side/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client-side:/app
